### ISSUE TITLE
Form Validation handling | Forgot Password 

### ISSUE THREAD

**Issue by aps08** [TeamShiksha/logoexecutive#219]
https://github.com/TeamShiksha/logoexecutive/blob/8a6ef8b04323c0719937eca5a456c9ad2eca1cbe/client/src/pages/forgot-password/ForgotPassword.js#L25

Look into the above code. It is written under an impression that the API all will always succeed. What will happen if the API call failed. There is no code I could see for showing error message if the API failed.

**Comment by aps08** [comment]
Work on this as priority

**Comment by Pratiyushkumar** [comment]
PR merged, hence closing the issue
