### ISSUE TITLE
Migrating from `firebase` to `mongodb`

### ISSUE THREAD

**Issue by amankumarsingh77** [TeamShiksha/logoexecutive#337]
### What is this issue related to?

Enhancement

### Description

Due to some performance and pricing issues a decision has been made to migrate our database from firebase to mongodb. 
1) Remove all the firebase code.
1) All the `services` that use firebase must be changes and made compatible to mongodb.
2) Re-write test for `services` that were changed.

### Expected Behavior

All the services must use `mongodb` instead of `firebase`.

### Current Behavior

All the services depends on `firebase` and its libraries.

### Additional Information (optional)

MongoDB nodejs docs:  https://www.mongodb.com/docs/drivers/node/current 
MongoDB testing library: https://jestjs.io/docs/mongodb, https://github.com/shelfio/jest-mongodb 

### Confirmation Checklist

- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.

**Comment by amankumarsingh77** [comment]
@amankumarsingh77 @Akash-27022002 @DeltaDynamo @sagarb2003 are assigned for this task.

**Comment by DeltaDynamo** [comment]
Hi Aman, I will be looking after the Keys Service part as of now. Will let you know about the progress made.

**Comment by sagarb2003** [comment]
Hey everyone , I will be writing code for Subscriptions.js and its test file

**Comment by amankumarsingh77** [comment]
I will be working on `ContactUs`, `UserToken` services.

**Comment by devwithakash** [comment]
Hii everyone I will be working on the `Users` service , model and their test cases

**Comment by itsarraj** [comment]
Assign me
