### ISSUE TITLE
Navigation Links Do Not Scroll to Top of Page on Click

### ISSUE THREAD

**Issue by Asin-Junior-Honore** [TeamShiksha/logoexecutive#338]
### What is this issue related to?

Performance

### Description

When clicking on a navigation link from the middle of the current page, the new page loads, but it does not start at the top. Instead, it opens at the same scroll position as the previous page.

### Expected Behavior

Clicking on a navigation link should take the user to the top of the new page.

### Current Behavior

Clicking on a navigation link takes the user to the same scroll position as the previous page.

### Additional Information (optional)

Consider adding code to reset the scroll position to the top when a navigation link is clicked.

### Confirmation Checklist

- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.

**Comment by Asin-Junior-Honore** [comment]
please assign this to me, I want to fix and rectify the issue

**Comment by aps08** [comment]
Allow us some time to check.

**Comment by Asin-Junior-Honore** [comment]
@aps08 alright

**Comment by samyak269** [comment]
please check and get the nav and footer to 100% width too? footer and nav bar produce irregular behaviour  both shrinking in size to full screen.

**Comment by Asin-Junior-Honore** [comment]
👋 hey 
@aps08 please could you please review my PR thanks
