### ISSUE TITLE
Add UI/UX enhancement for form validation.

### ISSUE THREAD

**Issue by anandbaraik** [TeamShiksha/logoexecutive#340]
### What is this issue related to?

Enhancement

### Description

When form validation fails. The message for the respective input field is shown but not below the input field, which can enhance the UI/UX for the user.  Right now, a failure message is shown above/below the form.

### Expected Behavior

A validation failure message should be shown just below the input field. For example, see below screenshot-

![image](https://github.com/user-attachments/assets/75817007-cc6b-467b-9d6e-624fa5f40486)
![image](https://github.com/user-attachments/assets/9dcc3e5b-8a2c-4163-953f-92c3018fd78d)
![image](https://github.com/user-attachments/assets/e6e75efa-fd2a-4d46-a011-8d452547b9df)
![image](https://github.com/user-attachments/assets/781dc1b9-07de-41eb-b4cb-a5f646a2f603)

### Current Behavior

A validation failure message is shown just above/below the form. For example, see below screenshot-
![image](https://github.com/user-attachments/assets/663127f9-a9e7-4da2-8e5a-1f2a8c84b1d7)
![image](https://github.com/user-attachments/assets/206a4595-32e3-42b2-940f-29023fd9e16d)

### Additional Information (optional)

 - Visit contact us/profile/dashboard etc. page and try submitting the form. 
- Consider adding validation message below input field to enhance UI/UX for the user.

### Confirmation Checklist

- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.

**Comment by asharma991** [comment]
Hey @aps08, please assign this to me. I'm halfway through it. Implemented everything, just need to modify tests now.
