### ISSUE TITLE
Add a button to Copy API endpoints.

### ISSUE THREAD

**Issue by anandbaraik** [TeamShiksha/logoexecutive#341]
### What is this issue related to?

Feature

### Description

Right now, There is no button to copy API endpoints. Adding a button to copy endpoint will be useful for users, and it'll significantly improve the user experience.

### Expected Behavior

There should be a button to copy the endpoint and once copied, it should show the message i.e. endpoint copied to clipboard.

![image](https://github.com/user-attachments/assets/96b5af02-109f-4f44-b448-de20ded158cc)

### Current Behavior

There is no button to copy endpoint.

![image](https://github.com/user-attachments/assets/4486bf52-24e2-40b5-8413-5040ba18a44e)

### Additional Information (optional)

Consider adding a button to copy endpoint.

### Confirmation Checklist

- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.

**Comment by aps08** [comment]
Invalid issue. The documentation you see here is coming from a .md file. So adding html content won't be possible here.
