### ISSUE TITLE
Implement One-Time API view/copy

### ISSUE THREAD

**Issue by buildwithankit** [TeamShiksha/logoexecutive#343]
### What is this issue related to?

Feature

### Description

Currently, when a user generates a new API key, they can copy the key as many times as they want. We need to implement one time view of API key.

### Expected Behavior

- When the user generates a new API key, the UI should display the newly generated API key along with a warning message.

- The warning message should be: "_Make sure to copy your API KEY now. You won’t be able to see it again!_"

- There should be a "Copy" button next to the displayed API key for easy copying to the clipboard.

- Remove API Key coloum from list of Keys in UI.

### Current Behavior

- When the user generates a new API key, they can copy the key as many times as they want.

### Additional Information (optional)

As we need to remove the Api Key coloum from the list of Keys we need to make changes in **fetchKeysByuserid**  service.

### Confirmation Checklist

- [X] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.

**Comment by RajputAnkit11** [comment]
@anandbaraik and I are assigned for this task.

**Comment by Sharathxct** [comment]
Can I work on this?

**Comment by aps08** [comment]
@DeltaDynamo
