### ISSUE TITLE
Forgot Password Email Contains “undefined” Instead of Reset Link

### ISSUE THREAD

**Issue by VinayakaHegade** [TeamShiksha/logoexecutive#362]
### Description

When clicking on the “Forgot Password” link in the app and providing an email address, the received email contains “undefined” instead of the actual password reset link.

### Expected Behavior

The email should contain a valid password reset link that allows the user to reset their password.

### Steps to Reproduce

1. Go to the login page of the app.
2. Click on the “Forgot Password” link.
3. Enter a registered email address and submit.
4. Check the received email for the password reset link.

### Screenshots or Recordings

![reset-password](https://github.com/user-attachments/assets/48806126-e969-4e3b-9acc-6b31b936fdd7)

### Confirmation Checklist

- [X] I have searched for similar issues [issues](https://github.com/TeamShiksha/logoexecutive/issues) and made sure no duplicate issue exists..
- [x] I have provided all the necessary information to understand and reproduce the bug.

**Comment by aps08** [comment]
Fixed has been applied and will be visible shortly on the live website. See the changes [here](https://github.com/TeamShiksha/logoexecutive/commit/137e480eb15bd0777a79dac318ac0814ae3f5bd0#diff-1522836f0e6c1a04202e48ffff3e0a3361e0fab4fa76614c4bd41dc93c935c35).
Thank you for highlighting this to us.
