### ISSUE TITLE
 Implement Proper Template for "Forget Password"

### ISSUE THREAD

**Issue by sujal111** [TeamShiksha/logoexecutive#368]
### What is this issue related to?

Enhancement

 Implement Proper Template for "Forget Password"

**Description:**

When users forget their credentials, they should have the ability to reset their password via the "Forget Password" option. Currently, while this option exists, the reset email does not have an appropriate template, and it lacks a proper greeting or salutation for the customers.

### Expected Behavior

- When a user clicks on the "Forget Password" option, they will receive an email with a well-structured template that includes:
  - A proper salutation ,
  - Clear instructions to reset their password
  - Professional and user-friendly messaging
  - A link to reset the password

### Current Behavior

- The "Forget Password" functionality is available, but the email template does not include a user-friendly greeting or any professional salutation, creating a less-than-ideal user experience.

### Additional Information (optional)

**Steps to Reproduce:**
1. Go to the login page.
2. Click on the "Forget Password" option.
3. Observe the email received for resetting the password.

### Confirmation Checklist

- [ ] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.

**Comment by aps08** [comment]
@sujal111, why is this not closed ?
