### ISSUE TITLE
Implement `Raise a Request` Functionality for Requesting Logos

### ISSUE THREAD

**Issue by computeronaldo** [TeamShiksha/logoexecutive#370]
### What is this issue related to?

Feature

### Description

User can raise a request for their company logo by providing their email ID and company url.

### Expected Behavior

1. On home page in **Try it now** section when user searches for a brand logo and doesn't find one an error message is displayed below  as **Logo Not Available**. Beneath this error message a section to **Raise a Request** will be added with a message **Couldn't find your logo try raising a request** and a button **Raise a Request**. Upon clicking this button a modal will open up which is a form asking for user email Id and company URL. Upon this form submission user's request for their logo is processed.

![annotely_image (1)](https://github.com/user-attachments/assets/a74a0c44-542b-4efd-a124-11e6ee1fb65e)

2. Corresponding APIs needs to be created to handle form submission.

### Current Behavior

1. There is no **Raise a Request** section for user to request their company logo upon failing to find their logo.

![Screenshot (233)](https://github.com/user-attachments/assets/23de0635-922a-4e9f-8389-7be056257055)

2. No backend APIs have been implemented yet to handle **Raise a Request** form submission.

### Additional Information (optional)

It's yet to be determined if existing schema is going to be used to handle **Raise a Request** feature or will be needing a new schema.

### Confirmation Checklist

- [ ] I have searched for similar issues before creating this one.
- [X] I have provided all the necessary information to understand and reproduce the issue.

**Comment by aps08** [comment]
This task is delayed by weeks.
