### ISSUE TITLE
Implement `repository` pattern/ separate business logic

### ISSUE THREAD

**Issue by amankumarsingh77** [TeamShiksha/logoexecutive#388]
### What is this issue related to?

Enhancement

### Description

We have decided to refactor our codebase to follow the `repository` pattern. This will improve code modularity, maintainability, and reliability by abstracting data access into repositories.
Also separates the data access layer from the business logic layer. 
**Tasks**
1. Modify repository interfaces for each entity.
2. Refactor services and controllers to use these repositories.
3. Update or create tests for the repository classes.

This change will help future-proof our code and make it easier to adapt to new data sources.

Assigned To:
@DeltaDynamo @ayush19sinha  @sujal111 @Rohan-Hazari @Soumava-221B @amoghar29 

### Expected Behavior

- Data access logic is abstracted into repository classes.
- Services and controllers interact with repository interfaces, not directly with the database.
- Increased flexibility, making it easier to mock data in tests and switch data sources in the future.

### Current Behavior

- Data access logic is directly embedded within `services` or `controllers`.
- `Controllers` are handling few logics that should be taken care by services.
- Limited flexibility and harder to test or switch data sources.

### Additional Information (optional)

NOTE: All the joi objects should be inside schema.js inside utils folder

### Confirmation Checklist

- [X] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.

**Comment by Soumava-221B** [comment]
I will be working on the controllers/public folder

**Comment by amoghar29** [comment]
I will be working on controllers/auth folder

**Comment by amankumarsingh77** [comment]
I will be working on the `user` controller and service

**Comment by sujal111** [comment]
I will be working on the Operator controller

**Comment by aps08** [comment]
Please take the latest pull from the monorepo branch.

**Comment by Rohan-Hazari** [comment]
I will be working on the business controller

**Comment by Rohan-Hazari** [comment]
Hi team I will be out of town from 6-10 November, will complete my task before 4

**Comment by Soumava-221B** [comment]
Hi team, 
i won't be available for the upcoming week days due to work commitments – thanks for understanding!
p.s. 
I've recently made updates in the server/controllers/public/search.js file. There are two other files in the public folder contact-us.js and logo.js that also need refactoring. If anyone is available, please feel free to take on the task of refactoring these two files.

Thank you!

**Comment by DeltaDynamo** [comment]
Hi Team, 
I will be working on Controllers/User

Update: User Controller is successfully migrated to monorepo setup through PR #404

**Comment by DeltaDynamo** [comment]
Update: Auth Controllers is migrated to monorepo setup through PR #416

**Comment by aps08** [comment]
50% completed.

**Comment by DeltaDynamo** [comment]
Business Controllers has been successfully migrated.

**Comment by DeltaDynamo** [comment]
Migration is complete. I am closing this issue.
Thanks to Everyone who worked on this.
cc: @aps08
