### ISSUE TITLE
Add Prettier, Eslint, husky, lint-staged in the `monorepo_setup` branch

### ISSUE THREAD

**Issue by aps08** [TeamShiksha/logoexecutive#390]
## Description

Adding eslint and prettier will make sure everyone follows the standard of the code. Both should run as part of `lint-staged` using `husky`.

## Expected Behavior
When ever someone commits the changed, the `husky` should run the commands provided pre-commit. The pre-commit commands should be eslint and prettier fixes. These commands should run in all the application inside `packages`.

## Current Behavior
No eslint or prettier.

## Notes
_- Reference repository [here](https://github.com/TeamShiksha/templates/tree/main/lerna-express-react-vitest-husky)._
_- Brand should be made from `monorepo_stepup` and PR should also be raised on the same branch._

### Confirmation Checklist

- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.

**Comment by a-s-t-e-y-a** [comment]
@aps08  can you assign me this issue

**Comment by aps08** [comment]
@a-s-t-e-y-a Are you part of [team.shiksha](https://team.shiksha/) discord server ?

**Comment by a-s-t-e-y-a** [comment]
Yes

**Comment by aps08** [comment]
Let's connect over there, and we can discuss. @a-s-t-e-y-a

**Comment by a-s-t-e-y-a** [comment]
okay
